import type { FoodMacros } from '@/database/schema';

export interface SeedFood extends FoodMacros {
  name: string;
  servingSize: number;
  servingUnit: string;
}

/**
 * Starter food list, weighted toward the Indian staples in the reference
 * tracker (dahi, chana, chapati, dal, soya chunks).
 *
 * These are approximate reference values for common preparations, offered as a
 * convenient starting point — the user can edit any of them, and the app does
 * not claim a licensed nutritional database. Everything here is created as a
 * normal user-owned food so it can be edited or deleted freely.
 */
export const SEED_FOODS: SeedFood[] = [
  {
    name: 'Milk (full fat)',
    servingSize: 500,
    servingUnit: 'ml',
    calories: 300,
    proteinG: 16,
    carbsG: 24,
    fatG: 16,
    fiberG: 0,
    sugarG: 24,
    sodiumMg: 215,
  },
  {
    name: 'Dahi (curd)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 61,
    proteinG: 3.5,
    carbsG: 4.7,
    fatG: 3.3,
    fiberG: 0,
    sugarG: 4.7,
    sodiumMg: 46,
  },
  {
    name: 'Chana (boiled chickpeas)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 164,
    proteinG: 8.9,
    carbsG: 27.4,
    fatG: 2.6,
    fiberG: 7.6,
    sugarG: 4.8,
    sodiumMg: 7,
  },
  {
    name: 'Matar (green peas)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 81,
    proteinG: 5.4,
    carbsG: 14.5,
    fatG: 0.4,
    fiberG: 5.1,
    sugarG: 5.7,
    sodiumMg: 5,
  },
  {
    name: 'Soya chunks (dry)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 345,
    proteinG: 52,
    carbsG: 33,
    fatG: 0.5,
    fiberG: 13,
    sugarG: 0,
    sodiumMg: 5,
  },
  {
    name: 'Whey protein',
    servingSize: 30,
    servingUnit: 'g scoop',
    calories: 120,
    proteinG: 24,
    carbsG: 3,
    fatG: 1.5,
    fiberG: 0,
    sugarG: 2,
    sodiumMg: 60,
  },
  {
    name: 'Rice (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 130,
    proteinG: 2.7,
    carbsG: 28,
    fatG: 0.3,
    fiberG: 0.4,
    sugarG: 0.1,
    sodiumMg: 1,
  },
  {
    name: 'Chapati',
    servingSize: 1,
    servingUnit: 'piece',
    calories: 104,
    proteinG: 3.1,
    carbsG: 18,
    fatG: 2.5,
    fiberG: 2.7,
    sugarG: 0.5,
    sodiumMg: 120,
  },
  {
    name: 'Dal (cooked)',
    servingSize: 150,
    servingUnit: 'g',
    calories: 180,
    proteinG: 11,
    carbsG: 27,
    fatG: 3,
    fiberG: 8,
    sugarG: 2,
    sodiumMg: 300,
  },
  {
    name: 'Egg (whole)',
    servingSize: 1,
    servingUnit: 'piece',
    calories: 72,
    proteinG: 6.3,
    carbsG: 0.4,
    fatG: 4.8,
    fiberG: 0,
    sugarG: 0.2,
    sodiumMg: 71,
  },
  {
    name: 'Paneer',
    servingSize: 100,
    servingUnit: 'g',
    calories: 296,
    proteinG: 20,
    carbsG: 3.4,
    fatG: 22,
    fiberG: 0,
    sugarG: 3.4,
    sodiumMg: 18,
  },
  {
    name: 'Banana',
    servingSize: 1,
    servingUnit: 'medium',
    calories: 105,
    proteinG: 1.3,
    carbsG: 27,
    fatG: 0.4,
    fiberG: 3.1,
    sugarG: 14,
    sodiumMg: 1,
  },
  {
    name: 'Peanut butter',
    servingSize: 32,
    servingUnit: 'g',
    calories: 190,
    proteinG: 8,
    carbsG: 6,
    fatG: 16,
    fiberG: 2,
    sugarG: 3,
    sodiumMg: 140,
  },
  {
    name: 'Oats (dry)',
    servingSize: 50,
    servingUnit: 'g',
    calories: 190,
    proteinG: 6.7,
    carbsG: 33,
    fatG: 3.4,
    fiberG: 5,
    sugarG: 0.5,
    sodiumMg: 2,
  },
  {
    name: 'Chicken breast (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 165,
    proteinG: 31,
    carbsG: 0,
    fatG: 3.6,
    fiberG: 0,
    sugarG: 0,
    sodiumMg: 74,
  },
];
