export {
  bestE1RM,
  calculateE1RM,
  calculateVolume,
  countWorkingSets,
  e1rmConfidence,
  E1RM_REP_LIMIT,
  heaviestSet,
  isWorkingSet,
  suggestProgression,
  totalReps,
  type E1RMInput,
  type EstimateConfidence,
  type ProgressionSuggestion,
  type VolumeOptions,
} from './strength';

export {
  addTotals,
  averageOf,
  calculateMacroTotals,
  clamp01,
  countDaysMeetingTarget,
  countDaysWithinRange,
  EMPTY_TOTALS,
  evaluateDay,
  evaluateMacro,
  scaleMacros,
  type AdherenceVerdict,
  type DayAdherence,
  type MacroAdherence,
  type MacroTotals,
} from './nutrition';

export {
  averageConsistency,
  calculateConsistency,
  calculateStreak,
  CONSISTENCY_CATEGORIES,
  DEFAULT_WEIGHTS,
  trainingScoreForDay,
  weightsFromConfig,
  type CategoryScores,
  type ConsistencyCategory,
  type ConsistencyResult,
  type StreakDay,
  type StreakResult,
} from './consistency';

export {
  calculateDelta,
  calculateTrend,
  compareExercise,
  EMPTY_PERIOD,
  MIN_SESSIONS_FOR_COMPARISON,
  movingAverage,
  percentagePointDelta,
  type ComparisonBasis,
  type ComparisonStatus,
  type Delta,
  type ExerciseComparison,
  type PeriodStats,
  type TrendDirection,
  type TrendResult,
} from './progress';
